global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    project: 'cryto-rates-demo'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']
      labels:
        instance: compose-host

  - job_name: 'pushgateway'
    scrape_interval: 30s
    static_configs:
    - targets: ['pushgateway:9091']
      labels:
        instance: compose-host
